### ISSUE TITLE
Additional Site: Perranporth and Slapton Sands

### ISSUE THREAD

**Issue by HelenD12** [SatelliteShorelines/coastsat_package#11]
I am currently working on an additional site: Perranporth and Slapton Sands and I will post the results once the work is complete.

I am unsure where to get the data from to create the tides.csv and waves_ERA5.csv files? Are there any instructions on how to do this?

I have looked at the CoastSat.slope example and followed the instructions to install the FES2014.

I am using example_jupyter.ipynb as a template and have completed the notebook until 4. Tidal correction. Any guidance or assistance  would be greatly appreciated.

**Comment by 2320sharon** [comment]
Hi Helen,

Thank you for raising this issue. The tide model download process is a common problem users of coastsat face because of this our team developed a new way to download and use the tide model so its faster to run and easier to download.

Make sure you install pyTMD into your coastsat_package environment before you download the tide model.

```
conda install -c conda-forge pyTMD
```

You can find instructions on how to download the tide model here: https://satelliteshorelines.github.io/CoastSeg/How-to-Download-Tide-Model/ . Once you have downloaded the tide model then you follow these steps to generate tide predictions.

Here is where we have a script that you can run to generate tide predictions:  https://github.com/SatelliteShorelines/CoastSeg/blob/main/scripts/predict_tides.py

This new script generates tide predictions using the tide model only for the exact dates a shoreline was extracted from the image, which is a bit different than CoastSat. I updated the `example.py` and `example_jupyter.ipynb` to use a new function to read these tide predictions that you'll need to update to. You'll need to update to 0.1.66  ,`pip install coastsat-package==0.1.66` and make sure you get the latest version of the `example_jupyter.ipynb` from github.

1. Choose a point
To use the new `tide_predictions` script you're first going to need to go https://geojson.io/#map=2/0/20 and place a point in the sea around parranporth. Save this point to geojson file. This is the location where the tide model will predict the tides.

![image](https://github.com/SatelliteShorelines/coastsat_package/assets/61564689/c5d38b4e-182d-4be1-83f9-25ca584629ff)

2. Get the transect_time_series.csv
 Then get your transect_time_series.csv file for the site you want to predict tides for. 
 
3. Download the Tide Model Regions file
- This file contains the regions the tide model was split into so tide predictions could run quicker: https://github.com/SatelliteShorelines/CoastSeg/blob/main/scripts/tide_regions_map.geojson
- The script needs to know where this file is so it knows which region of the tide model the point belongs to and uses that tide model to predict the tides

 4. Run predict_tides.py
 Once you have these and downloaded the tide model using the guide above. You'll run a the script like this:

(Make sure to replace these with the locations of your files)

```
python predict_tides.py -C "C:\Users\sf230\Downloads\parranporth.geojson" -T "C:\development\doodleverse\coastsat_package\coastsat_package\data\NARRA\transect_time_series.csv"  -M "C:\development\doodleverse\coastseg\CoastSeg\tide_model" -R "C:\development\doodleverse\coastseg\CoastSeg\scripts\tide_regions_map.geojson"
```

`-C <location of the geojson file from step 1>`
`-T <location of the timeseries file from step 2>`
`-M <location of the tide model you downloaded>`

This will create a file called tidal_predictions.csv and you can use this file in the new `example_jupyter.ipynb` notebook to perform tide predictions.

As for the waves dataset you mentioned @dbuscombe-usgs can you help with this.

We also released a guide on how to use predict tides at our CoastSeg website: https://satelliteshorelines.github.io/CoastSeg/how_to_predicts_tides_script/

**Comment by ddbuscombe** [comment]
Thanks for this Sharon. Yes, I can help with the ERA5 data. I am preparing a script for general use now and will provide it soon.

**Comment by ddbuscombe** [comment]
After 3 days of work, I'm edging towards a solution. This is far trickier than I thought to develop because the cdsapi is so badly documented. @HelenD12 can you please be a bit more specific as to your needs? Thanks

**Comment by HelenD12** [comment]
Thanks for both your responses this is much appreciated. 

Thanks @2320sharon I will let you know how I get on when I have a chance to run the tides script, but this looks perfect for the Perranporth data set.

@dbuscombe-usgs thanks for preparing a script for general use. I was a bit lost as to where to even start with this. I would be running this for the benchmark data I have for Perranporth, UK for the time period 2015 - 2023. I'm not sure if I have answered your question. I appreciate any help you are able to provide.

**Comment by ddbuscombe** [comment]
Thanks @HelenD12 . I ended up making a script and putting it [here](https://github.com/Doodleverse/SDStools/blob/main/scripts/download_era5_dataframe_singlelocation.py) inside a new toolbox that, when more developed, will be moved here to the SatShores organization. It requires [cdsapi](https://pypi.org/project/cdsapi/) and assumes the API and credentials are stored in file. Follow the instructions at https://pypi.org/project/cdsapi/ for how to obtain and store credentials.

It also needs xarray, numpy, pandas, matplotlib, seaborn, and datetime libraries. You'll need to set up the python environment yourself to run the script.

I used the script to download wave data at two locations, one inshore and one further offshore. The files are here:
[perranporth_offshore_reanalysis-era5-single-levels_swh_mwp_pp1d_mwd_wp_-5.1876_50.3697_1984_2023.csv](https://github.com/SatelliteShorelines/coastsat_package/files/15241975/perranporth_offshore_reanalysis-era5-single-levels_swh_mwp_pp1d_mwd_wp_-5.1876_50.3697_1984_2023.csv)

[perranporth_reanalysis-era5-single-levels_swh_mwp_pp1d_mwd_wp_-5.166_50.366_1984_2023.csv](https://github.com/SatelliteShorelines/coastsat_package/files/15241976/perranporth_reanalysis-era5-single-levels_swh_mwp_pp1d_mwd_wp_-5.166_50.366_1984_2023.csv)

Note that I didn't check the water depth for the inshore site, so it is possible that the deep-water equations I used to compute wave setup and wavepower may not apply here.

The script also auto-generates some plots, mostly for QA/QC

![perranporth_offshore_reanalysis-era5-single-levels_timeseries_Hs](https://github.com/SatelliteShorelines/coastsat_package/assets/3596509/efb10578-e706-491d-bcce-f6a9f1081b51)

![perranporth_offshore_reanalysis-era5-single-levels_joint_and_marginal_distributions_Hs_Tmean](https://github.com/SatelliteShorelines/coastsat_package/assets/3596509/522ab0d7-4efc-4e28-8c34-ae13d3f462bf)

![perranporth_offshore_reanalysis-era5-single-levels_joint_and_marginal_distributions_Hs_Tpeak](https://github.com/SatelliteShorelines/coastsat_package/assets/3596509/1355f39e-5a8c-4f4d-ab25-99b258395c67)

![perranporth_offshore_reanalysis-era5-single-levels_joint_and_marginal_distributions_Hs_Dmean](https://github.com/SatelliteShorelines/coastsat_package/assets/3596509/03d62a7a-02b1-4875-8376-6032886e99a8)

I'll download data from Slapton now

(fun fact, I was involved in setting up both long-term monitoring campaigns - at Slapton in 2004/2005, and at Perranporth a year or so later. It's great to see you working up these SDS data!!! But why stop at 2015?)

**Comment by ddbuscombe** [comment]
Here is data from a location offshore of Slapton

[slapton_reanalysis-era5-single-levels_swh_mwp_pp1d_mwd_wp_-3.608_50.278_1984_2023.csv](https://github.com/SatelliteShorelines/coastsat_package/files/15242343/slapton_reanalysis-era5-single-levels_swh_mwp_pp1d_mwd_wp_-3.608_50.278_1984_2023.csv)

![slapton_reanalysis-era5-single-levels_timeseries_Hs](https://github.com/SatelliteShorelines/coastsat_package/assets/3596509/414eded3-47a8-48da-b1dd-72d7f0788279)

![slapton_reanalysis-era5-single-levels_joint_and_marginal_distributions_Hs_Tpeak](https://github.com/SatelliteShorelines/coastsat_package/assets/3596509/fcdd111f-1b7a-4e53-b0e1-454cf2791b4d)
![slapton_reanalysis-era5-single-levels_joint_and_marginal_distributions_Hs_Tmean](https://github.com/SatelliteShorelines/coastsat_package/assets/3596509/fb801c77-78d1-4b73-b892-af052d93ca77)
![slapton_reanalysis-era5-single-levels_joint_and_marginal_distributions_Hs_Dmean](https://github.com/SatelliteShorelines/coastsat_package/assets/3596509/d63e3196-b693-473b-a62e-e97e5039466d)

Variable names:
swh = significant wave height of combined sea and swell, in m
mwp = mean wave period, s
pp1d = peak wave period, s
mwd = mean wave direction, deg N
wp = wave power (offshore assumption) in kW (per unit m)
ws = wave setup (offshore assumption) in m

**Comment by ddbuscombe** [comment]
![slapton_inshore_reanalysis-era5-single-levels_timeseries_Hs](https://github.com/SatelliteShorelines/coastsat_package/assets/3596509/64ca69ef-1da1-4326-a037-9d9bc2ced29b)
[slapton_inshore_reanalysis-era5-single-levels_swh_mwp_pp1d_mwd_wp_-3.627_50.2811_1984_2023.csv](https://github.com/SatelliteShorelines/coastsat_package/files/15242366/slapton_inshore_reanalysis-era5-single-levels_swh_mwp_pp1d_mwd_wp_-3.627_50.2811_1984_2023.csv)

Here's a slightly more inshore record for Slapton

**Comment by ddbuscombe** [comment]
I think issue is now resolved. Feel free to reopen if not.

**Comment by ddbuscombe** [comment]
In fact this is really an SDSTools issue (https://github.com/Doodleverse/SDStools) and nothing to do with coastsat-package, so that would be a better place for further discussion. I plan on further refining the scripts at some point.
